### ISSUE TITLE
#1 경험치 올리는 부분 수정 필요

### ISSUE THREAD

**Issue by gjlee0802** [gjlee0802/PokemonConsoleGame#1]
https://github.com/gjlee0802/PokemonConsoleGame/blob/99d05f5efc21810bdfe700ce59c7e6f58b37c8fa/windows/windows/main.cpp#L176

`		if (Sptr->enemyPokeHealth <= 0)
		{
			setColor(10, 0);
			printf(">> 상대 포켓몬이 쓰러졌다!\n");
			Sleep(1500);
			Sptr->myPokeExp[0] = Sptr->myPokeExp[0] + (Sptr->enemyPokeLevel) * (Sptr->enemyPokeLevel) * (Sptr->enemyPokeLevel);
			//얻는 경험치는 상대포켓몬 레벨**3으로 설정
			printf(">> 경험치가 %d만큼 증가했다!\n", (Sptr->enemyPokeLevel) * (Sptr->enemyPokeLevel) * (Sptr->enemyPokeLevel));
			Sleep(1500);
			if (Sptr->myPokeExp[0] >= Sptr->LevelUpExp[0]) {
				while (Sptr->myPokeExp[0] >= Sptr->LevelUpExp[0]){
					Sptr->myPokeExp[0] = Sptr->myPokeExp[0] - Sptr->LevelUpExp[0];
					Sptr->myPokeLevel[0] += 1;
					Sptr->LevelUpExp[0] = (Sptr->myPokeLevel[0] + 1) * (Sptr->myPokeLevel[0] + 1) * (Sptr->myPokeLevel[0] + 1);
					printf(">> 레벨이 1 증가했다!\n");
					Sleep(1500);
				}
			}
			printf(">> 레벨이 %d(이)가 되었다!\n", Sptr->myPokeLevel[0]);
			Sleep(2000);
			break;
		}
`

야생 포켓몬을 처치(마무리)한 포켓몬의 경험치만 오르도록 하려면
"Sptr->myPokeExp[0]"를 "Sptr->myPokeExp[Sptr->currPokeIndex]"으로 수정 필요.
(인덱스에 0이 들어가면 처음순서의 포켓몬만 경험치가 오른다.)

만약, 하나의 포켓몬만 경험치가 오르는 것이 아니라 처치에 기여한 모든 포켓몬의 경험치를 올리게끔하려면 새로운 처치기여 포켓몬의 목록을 담는 Sequence를 만들고 반복문을 통해 Sequence에 포함되어 있는 포켓몬들의 경험치를 적절히 올린다.

**Comment by junhahn00** [comment]
열심히 하세요~

**Comment by gjlee0802** [comment]
수정완료.

**Comment by junhahn00** [comment]
확인했습니다.
